name    'puppetlabs-denyhosts'
version '0.0.1'
source  'https://github.com/puppetlabs/puppetlabs-denyhosts'
author  'Puppet Labs'
license 'Apache License, Version 2.0'
summary 'Configure DenyHosts'
description 'Configure DenyHosts'
project_page 'https://github.com/puppetlabs/puppetlabs-denyhosts'
